### ISSUE TITLE
[GSoC] IRC Meeting and Communication Modes

### ISSUE THREAD

**Issue by Polaris000** [chaoss/governance#135]
Regarding the GSoC project [Implementing CHAOSS metrics with Perceval](https://summerofcode.withgoogle.com/projects/#6557010399592448), the common modes of communication would be the following: 
- Bi-weekly meetings with mentors on the channel `#grimoirelab` on freenode
- Emails on the mailing lists with links to my latest weekly blog posts. 

The posts will live on my [website](https://polaris000.github.io), but will be linked here as comments to this issue. 

The logs of the IRC meetings will be contained in my GSoC repository [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations)

**Comment by Polaris000** [comment]
My first two blog posts!
- The [first one](https://polaris000.github.io/blog/pre-gsoc) talks about my experience contributing to open source and the journey before the selection
- The [second one](https://polaris000.github.io/blog/com_bonding_1) is in regards to the first community bonding meeting with my mentors

The log of this meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/may_16_comm_bonding.txt).

**Comment by germonprez** [comment]
Nice to see these @Polaris000. Thanks for sharing 🥇

**Comment by Polaris000** [comment]
My latest blog post can be found [here](https://polaris000.github.io/blog/com_bonding_2)

The log of the latest meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/may_24_comm_bonding.txt).

**Comment by Polaris000** [comment]
**Week1**
My blog post can be found [here](https://polaris000.github.io/blog/week_1)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/may_31_comm_bonding.txt).

**Comment by Polaris000** [comment]
**Week2**
My blog post can be found [here](https://polaris000.github.io/blog/week_2)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/june_7_week2.txt).

**Comment by Polaris000** [comment]
**Week3**
My blog post can be found [here](https://polaris000.github.io/blog/week_3)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/june_14_week3.txt).

**Comment by Polaris000** [comment]
**Week4**

The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/june_24_week4.txt).

**Comment by Polaris000** [comment]
**Evaluation week 1**
My blog post can be found [here](https://polaris000.github.io/blog/eval_1)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/june_28_eval1.txt).

**Comment by Polaris000** [comment]
**Week5 **
My blog post can be found [here](https://polaris000.github.io/blog/week_5)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/july_5_week5.txt).

**Comment by Polaris000** [comment]
**Week6**
My blog post can be found [here](https://polaris000.github.io/blog/week_6)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/july_16_week6.txt).

**Comment by Polaris000** [comment]
**Week7 and Evaluation week 2**
My blog post can be found [here](https://polaris000.github.io/blog/week_7_8)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/july_26_week7_8.txt).

**Comment by Polaris000** [comment]
**Week8**
My blog post can be found [here](https://polaris000.github.io/blog/week_8)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/aug_6_week8.txt).

**Comment by Polaris000** [comment]
**Week9**
My blog post can be found [here](https://polaris000.github.io/blog/week_9)
The log of the meeting can be found [here](https://github.com/Polaris000/GSoC_19_Perceval_Implementations/blob/master/IRC_chats/aug_13_week9.txt).

**Comment by Polaris000** [comment]
Since the GSoC coding period ended a while back, I'm closing this issue.
