### ISSUE TITLE
Update GCoC Pages

### ISSUE THREAD

**Issue by germonprez** [chaoss/governance#146]
@GeorgLink -- I think that we should clear out the two GSoC pages. I think that we can leave a lot of the content, just remove the text that is associated with last summer. What do you think?

**Comment by GeorgLink** [comment]
Yes, I agree. That's what we did last year too.

**Comment by germonprez** [comment]
@sgoggins @valeriocos @dicortazar @sanacl 

I'm pinging you guys as involved with GSoC in the last few years. Like prior years, we need to update our Ideas Page for potential students: 

https://github.com/chaoss/governance/blob/master/GSoC-Ideas.md

I've also captured all ideas that have been shared across the CHAOSS project here: 

https://docs.google.com/document/d/1idoDg-5M7Dte0SWNB8AdsR7E3cJyGsCp8KrK3QBpGBE/edit#heading=h.o3hw1vl7cf0

In all, I think we need about four ideas from GrimoireLab and Augur. Our deadline is Feb 5 so if we could get these updated by the Feb 3 or 4, that would be excellent.

**Comment by jgbarah** [comment]
This year I won't be able of leading GSoC projects, but I will try to support others who lead them, mainly in those related to GrimoireLab.
