### ISSUE TITLE
proposal link

### ISSUE THREAD

**Issue by GouravSardana** [chaoss/governance#19]
I forget to add link of my proposal.
Should i add??

**Comment by GeorgLink** [comment]
Yes

**Comment by GouravSardana** [comment]
on pull request??

**Comment by GeorgLink** [comment]
Yes, create a pull request for it.

**Comment by GouravSardana** [comment]
I create a pull request. You can check @GeorgLink

**Comment by GouravSardana** [comment]
You can review it and ask me for changes. After your review I finally submitted to gsoc.
