### ISSUE TITLE
Merge all GSoC proposals

### ISSUE THREAD

**Issue by germonprez** [chaoss/governance#195]
@GeorgLink can we merge all the GSoC PRs in one consolidated merge?

**Comment by GeorgLink** [comment]
We should merge PRs individually. If I created a consolidated commit with everything I think that's more work and it's harder to track who are the original authors.

**Comment by germonprez** [comment]
Is there a simple solution to merge the many PRs without creating conflicts, one after the other?

**Comment by GeorgLink** [comment]
Not that I am aware of. Sorry 😔

I assume this is obsolete after we discussed how to resolve merge conflicts.
