### ISSUE TITLE
[GSoC] Project Updates (287)

### ISSUE THREAD

**Issue by vchrombie** [chaoss/governance#205]
Opening this issue to provide information about the updates on the project idea [Creating Quality models using GrimoireLab and CHAOSS metrics](https://summerofcode.withgoogle.com/projects/#5489558193438720) (https://github.com/chaoss/grimoirelab/issues/287).

I have created a project tracker repository for storing the progress, weekly summaries, and meeting logs. The link to the repository is https://github.com/vchrombie/gsoc.

The communication would be as follows:
- Weekly meetings with mentors on the channel `#grimoirelab` on Freenode IRC. The meeting logs will be stored in the [meetings](https://github.com/vchrombie/gsoc/tree/master/meetings) folder of the project tracker, right after the meeting. I will share the meeting log here as well.
- Weekly blog posts on my [blog](https://vchrombie.github.io/blog/), will be sharing the links here as well.
- The weekly work summary will be shared with the GrimoireLab mailing list. They are also stored in the [work](https://github.com/vchrombie/gsoc/tree/master/work) folder of the project tracker.
- The weekly blog posts are sent to the CHAOSS mailing list too.**\***

Thanks to the mentors, @inishchith @Polaris000 @dlumbrer @valeriocos, for the help.
Please let me know if you have any suggestions. :smiley:

**Comment by GeorgLink** [comment]
Thanks Venu!
Could you please also send your blog posts to the CHAOSS mailing list?
Not everyone is actively paying attention to GitHub updates.

Best,
Georg

**Comment by vchrombie** [comment]
> Thanks Venu! Could you please also send your blog posts to the CHAOSS mailing list? Not everyone is actively paying attention to GitHub updates.

Sure, @GeorgLink. I don't have any problems. I will be sending the weekly blog posts and updates to the mailing list too.

**Comment by GeorgLink** [comment]
Thank you :-)

**Comment by vchrombie** [comment]
#### GSoC Acceptance

Blog Post: [aceptación gsoc](https://vchrombie.github.io/blog/gsoc-acceptance)

**Comment by vchrombie** [comment]
#### Community Bonding Week-1

Meeting log: [07-05-2020-community-bonding-1.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/07-05-2020-community-bonding-1.txt)
Work Report: [cb-week-1 report](https://github.com/vchrombie/gsoc/blob/master/work/community-bonding#week-1-summary)
Blog Post: [unión comunitaria 1](https://vchrombie.github.io/blog/community-bonding-1)

**Comment by vchrombie** [comment]
#### Community Bonding Week-2

Meeting log: [14-05-2020-community-bonding-2.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/14-05-2020-community-bonding-2.txt)
Work Report: [cb-week-2 report](https://github.com/vchrombie/gsoc/blob/master/work/community-bonding#week-2-summary)
Blog Post: [unión comunitaria 2](https://vchrombie.github.io/blog/community-bonding-2)

**Comment by vchrombie** [comment]
#### Community Bonding Week-3

Meeting log: [21-05-2020-community-bonding-3.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/21-05-2020-community-bonding-3.txt)
Work Report: [cb-week-3 report](https://github.com/vchrombie/gsoc/blob/master/work/community-bonding#week-3-summary)
Blog Post: [unión comunitaria 3](https://vchrombie.github.io/blog/community-bonding-3)

**Comment by vchrombie** [comment]
#### Community Bonding Week-4

Meeting log: [28-05-2020-community-bonding-4.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/28-05-2020-community-bonding-4.txt)
Work Report: [cb-week-4 report](https://github.com/vchrombie/gsoc/blob/master/work/community-bonding#week-4-summary)
Blog Post: [unión comunitaria 4](https://vchrombie.github.io/blog/community-bonding-4)

**Comment by vchrombie** [comment]
#### Coding Period 1 Week-1

Meeting log: [2020-06-04-coding-period-1-week-1.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-06-04-coding-period-1-week-1.txt)
Work Report: [cp-1-week-1 report](https://github.com/vchrombie/gsoc/blob/master/work/week-1/#week-1-summary)
Blog Post: [semana uno](https://vchrombie.github.io/blog/coding-period-1-week-1)

**Comment by vchrombie** [comment]
#### Coding Period 1 Week-2

Meeting log: [2020-06-11-coding-period-1-week-2.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-06-11-coding-period-1-week-2.txt)
Work Report: [cp-1-week-2 report](https://github.com/vchrombie/gsoc/blob/master/work/week-2/#week-2-summary)
Blog Post: [semana dos](https://vchrombie.github.io/blog/coding-period-1-week-2)

**Comment by vchrombie** [comment]
#### Coding Period 1 Week-3

Meeting log: [2020-06-19-coding-period-1-week-3.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-06-19-coding-period-1-week-3.txt)
Work Report: [cp-1-week-3 report](https://github.com/vchrombie/gsoc/blob/master/work/week-3/#week-3-summary)
Blog Post: [semana tres](https://vchrombie.github.io/blog/coding-period-1-week-3)

**Comment by vchrombie** [comment]
#### Coding Period 1 Week-4

Meeting log: [2020-06-25-coding-period-1-week-4.md](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-06-25-coding-period-1-week-4.md)
Work Report: [cp-1-week-4 report](https://github.com/vchrombie/gsoc/blob/master/work/week-4/#week-4-summary)
Blog Post: [semana cuatro](https://vchrombie.github.io/blog/coding-period-1-week-4)

**Comment by vchrombie** [comment]
#### Coding Period 1 Week-5

Meeting log: [2020-07-02-coding-period-1-week-5.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-07-02-coding-period-1-week-5.txt)
Work Report: [cp-1-week-5 report](https://github.com/vchrombie/gsoc/blob/master/work/week-5/#week-5-summary)
Blog Post: [semana cinco](https://vchrombie.github.io/blog/coding-period-1-week-5)

**Comment by vchrombie** [comment]
#### Coding Period 2 Week-6

Meeting log: [2020-07-09-coding-period-2-week-6.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-07-09-coding-period-2-week-6.txt)
Work Report: [cp-2-week-6 report](https://github.com/vchrombie/gsoc/tree/master/work/week-6#week-6-summary)
Blog Post: [semana seis](https://vchrombie.github.io/blog/coding-period-2-week-6)

**Comment by vchrombie** [comment]
#### Coding Period 2 Week-7

Meeting log: [2020-07-16-coding-period-2-week-7.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-07-16-coding-period-2-week-7.txt)
Work Report: [cp-2-week-7 report](https://github.com/vchrombie/gsoc/tree/master/work/week-7#week-7-summary)
Blog Post: [semana siete](https://vchrombie.github.io/blog/coding-period-2-week-7)

**Comment by vchrombie** [comment]
#### Coding Period 2 Week-8

Meeting log: [2020-07-23-coding-period-2-week-8.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-07-23-coding-period-2-week-8.txt)
Work Report: [cp-2-week-8 report](https://github.com/vchrombie/gsoc/tree/master/work/week-8#week-8-summary)
Blog Post: [semana ocho](https://vchrombie.github.io/blog/coding-period-2-week-8)

**Comment by vchrombie** [comment]
#### Coding Period 2 Week-9

Meeting log: [2020-07-30-coding-period-2-week-9.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-07-30-coding-period-2-week-9.txt)
Work Report: [cp-2-week-9 report](https://github.com/vchrombie/gsoc/tree/master/work/week-9#week-9-summary)
Blog Post: [semana nueve](https://vchrombie.github.io/blog/coding-period-2-week-9)

**Comment by vchrombie** [comment]
#### Coding Period 3 Week-10

Meeting log: [2020-08-06-coding-period-3-week-10.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-08-06-coding-period-3-week-10.txt)
Work Report: [cp-3-week-10 report](https://github.com/vchrombie/gsoc/tree/master/work/week-10#week-10-summary)
Blog Post: [semana diez](https://vchrombie.github.io/blog/coding-period-3-week-10)

**Comment by vchrombie** [comment]
#### Coding Period 3 Week-11

Meeting log: [2020-08-13-coding-period-3-week-11.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-08-13-coding-period-3-week-11.txt)
Work Report: [cp-3-week-11 report](https://github.com/vchrombie/gsoc/tree/master/work/week-11#week-11-summary)
Blog Post: [semana once](https://vchrombie.github.io/blog/coding-period-3-week-11)

**Comment by vchrombie** [comment]
#### Coding Period 3 Week-12

Meeting log: [2020-08-20-coding-period-3-week-12.txt](https://github.com/vchrombie/gsoc/blob/master/meetings/2020-08-20-coding-period-3-week-12.txt)
Work Report: [cp-3-week-12 report](https://github.com/vchrombie/gsoc/tree/master/work/week-12#week-12-summary)
Blog Post: [semana doce](https://vchrombie.github.io/blog/coding-period-3-week-12)

**Comment by vchrombie** [comment]
Closing this issue since we have completed the project. :smile:
