### ISSUE TITLE
Confusion regarding GSoD proposal

### ISSUE THREAD

**Issue by tharun143** [chaoss/governance#209]
Hey, I went through the season of docs technical writer guide and found that the applicant has to submit the description and title in the [form](https://docs.google.com/forms/d/e/1FAIpQLSecVnkiamFJntE1iuguc-UXIQFCKOtKlq4S1o6I1QRjQKv4vQ/viewform). But as per the GSoD-interest.md, the applicants need to submit the proposal link. As there is no specific format for the GSoD proposal. So, how do I need to proceed further? 

@vchrombie @GeorgLink Can you please look in to this.

**Comment by vchrombie** [comment]
Hi @tharun143 
I read the guidelines. I know the application is a form. 

I would suggest a thing, maybe you can follow if the idea is good enough.

You can create a google doc, let's call it as the (draft) proposal and you can write answers to all the questions, which are there in the form, in this doc. I saw a few questions in the form like

```
> Title of technical writing project proposal
Supply a short, descriptive title that summarizes the main goal of the work you're proposing. If based on a project idea proposed by the open-source organization, use the title of that project idea.

> Description of technical writing project proposal
Give as much detail as possible in the description of the technical writing project that you're proposing. It's fine to enter multiple paragraphs in the description field.
```


This would be better as you can edit these answers and you have a chance to improve them whenever it is possible. And when you are submitting the form, copy-paste the answers from the document to the form directly.

I would suggest you can submit the same above document as the link to the proposal.

@GeorgLink @germonprez 
WDYT?

**Comment by germonprez** [comment]
Yea, I see the issue. With GSoC, applicants could point to a repo. In this case, we don't have that. I do like @vchrombie's idea of having applicants post the relevant components from the Google application form as a Google Doc or a Markdown file.

**Comment by GeorgLink** [comment]
+1 @vchrombie

**Comment by vchrombie** [comment]
Hi @tharun143, thanks for raising the question.

> You can create a google doc, let's call it as the (draft) proposal and you can write answers to all the questions, which are there in the form, in this doc. I saw a few questions in the form like 
> This would be better as you can edit these answers and you have a chance to improve them whenever it is possible. And when you are submitting the form, copy-paste the answers from the document to the form directly.
> I would suggest you can submit the same above document as the link to the proposal.

Do you think this is feasible?

**Comment by tharun143** [comment]
@vchrombie Yes, it's feasible and I am working on it. Thanks for the idea 😄
