### ISSUE TITLE
Talk to the mentors

### ISSUE THREAD

**Issue by GouravSardana** [chaoss/governance#23]
I want to talk to the mentors of idea #3 prototype new CHAOSS Metrics.
Kindly provide their email or some other things where I can chat regarding the implementation of the project.

**Comment by GouravSardana** [comment]
@sgoggins I want to talk to you about the implementation regarding prototype new chaoss metrics that what all of you are planning?

**Comment by sgoggins** [comment]
Hi Gourav,

The priority metrics are those in the https://github.com/chaoss/metrics/blob/master/2_Growth-Maturity-Decline.md#community-growth <https://github.com/chaoss/metrics/blob/master/2_Growth-Maturity-Decline.md#community-growth>

section of growth, maturity and decline. Any of the Growth, Maturity & Decline; Risk and Value sections are also good choices.  Diversity and Inclusion Metrics may have some candidates, but many of those will require more than only repository data. 

Sean
