### ISSUE TITLE
[Notes] The release version number are different between this time and before

### ISSUE THREAD

**Issue by king-gao** [chaoss/governance#232]
In the CHAOSS project homepage , URL : https://chaoss.community/release-history/

we rule the releasr version number is "YYYY-MM" in chaoss project ,like this:
![image](https://user-images.githubusercontent.com/58930496/92210165-cb4a5800-eec0-11ea-90b1-a73c34de3b70.png)
 but I found the releasr version number before this time is like this:
![image](https://user-images.githubusercontent.com/58930496/92209858-49f2c580-eec0-11ea-992b-0428f189f0eb.png).

**Comment by GeorgLink** [comment]
Thanks for noticing @king-gao 
Yes, this is correct. 
We got the feedback that we should add the hyphen and consequently changed the version number format.

The format we use is documented in our CHAOSS Community Handbook:
https://github.com/chaoss/governance/blob/master/community-handbook/metrics-release.md
