### ISSUE TITLE
Templates for focus-areas READMEs in WGs

### ISSUE THREAD

**Issue by ritik-malik** [chaoss/governance#276]
Hi everyone,

Right now, the focus-areas READMEs in each WG have a different structure. For eg -
* [wg-value/focus-areas](https://github.com/chaoss/wg-value/tree/master/focus-areas)
* [wg-diversity-inclusion/focus-areas](https://github.com/chaoss/wg-diversity-inclusion/tree/master/focus-areas)
* [wg-common/focus-areas](https://github.com/chaoss/wg-common/tree/master/focus-areas)

Also, each focus-area have different structure for READMEs too. For eg -
* [wg-common/focus-areas/what](https://github.com/chaoss/wg-common/tree/master/focus-areas/what)
* [wg-risk/focus-areas/licensing](https://github.com/chaoss/wg-risk/tree/master/focus-areas/licensing)
* [wg-evolution/focus-areas/code-development-activity](https://github.com/chaoss/wg-evolution/tree/master/focus-areas/code-development-activity)

As discussed, I prepared 2 templates -

1. Template for Focus-areas READMEs
2. Template for README in each focus area

The templates can be found in [this document](https://docs.google.com/document/d/12cac1TA_xTpUCcoTWg3e_03-m22CjLelTioaXRrTnpo/edit?usp=sharing)

All suggestions and improvements are welcome.

**Comment by germonprez** [comment]
Hi @ritik-malik 

We are considering this. For example, there is an issue in every WG. Here is the one in DEI: 

https://github.com/chaoss/wg-diversity-inclusion/issues/358

**Comment by ritik-malik** [comment]
Whoops! My bad,
I thought those issues were only for the main README

**Comment by germonprez** [comment]
No problem! Feel free to include ideas that you have that may not be captured in the current proposal.

**Comment by ritik-malik** [comment]
Hmm I guess the focus-area READMEs aren't mentioned in the current proposal

**Comment by germonprez** [comment]
Ah. I see. Yours are located more in the lower-level folders.

**Comment by GeorgLink** [comment]
The document looks good. Thanks for putting this together

**Comment by ritik-malik** [comment]
The templates are merged, we can close this issue now
