### ISSUE TITLE
talk to mentors

### ISSUE THREAD

**Issue by theexplorist** [chaoss/governance#58]
sir now i know the problem, i did not filled the GSOC applying application ,i thought GSOC proposal is the application,so i just completed the micro task and made a proposal. I think mine chance is gone for this time. Sir how many times can i try now ? I want to work with CHAOSS only.

**Comment by theexplorist** [comment]
And thanks for helping me .

**Comment by GeorgLink** [comment]
You are very welcome to work with CHAOSS. We address an issue that many
companies and open source projects care about and you can learn valuable
skills with us. I suggest joining our weekly calls and findings things to
do.

**Comment by theexplorist** [comment]
i will sir

**Comment by theexplorist** [comment]
i just pased my sophomore year so can i apply for GSOC  next time with ur org

**Comment by theexplorist** [comment]
Actually i was unaware that i have to fill a GSOC application separately ,and that sacked my chances , i was very much eager to work.

**Comment by GeorgLink** [comment]
Okay.

**Comment by theexplorist** [comment]
I think the deadline to fill form is over.

**Comment by GeorgLink** [comment]
Yes, the deadline has passed. You can apply again next year.
