### ISSUE TITLE
Feedback regarding GSoC

### ISSUE THREAD

**Issue by karansingh1559** [chaoss/governance#63]
Hey @jgbarah @valeriocos thanks for helping me, to get through the process of writing a GSoC proposal. Unfortunately, my project did not get selected. This was my first time in GSoC and I would like to know any shortcomings in my proposal that you might have come across, so that I can apply to GSoC in a better way.

**Comment by jgbarah** [comment]
Thanks a lot for trying GSoC with us, and for your interest in the CHAOSS and GrimoireLab projects. We received a lot of good proposals, and finally we had to decide on those that we thought fitted better in the context of the projects. This does not say anything against you, your proposals, or your skills, and I encourage you to try GSoC again next year, if that is convenient for you. And of course, if you want to stay participating in our community, I will be happy to help.

If you see me in the IRC channel and want to chat about this, please ping me there.
