### ISSUE TITLE
connect with organisation

### ISSUE THREAD

**Issue by theexplorist** [chaoss/governance#67]
Sir, i have previously worked and completed a microtask with your organisation. Sir i want to know how i can attend your calls and want to know about the conference dated 28 august.

**Comment by geekygirldawn** [comment]
Hi, the information about the conference can be found on our [website](https://chaoss.community/chaosscon-2018-na/). We expect to announce the schedule and names of the presenters in the next 1 or 2 weeks. Information about the calls and other discussions about the project can be found on the [mailing list](https://lists.linuxfoundation.org/pipermail/oss-health-metrics/).

**Comment by jgbarah** [comment]
I think it is time to close this...
