### ISSUE TITLE
Document prefixes for emails that we will use on the mailing list

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/governance#8]
We talked about merging all mailing lists into one. The idea is to use prefixes to denote what topic an email falls into. We should create a list of prefixes and thus document them. With that in place, we can use filters in our own mail clients.

**Comment by GeorgLink** [comment]
Audiences (require exactly one):
[all] - to address the whole CHAOSS community
[software] - to address the software committee
[metrics] - to address the metrics committee
[d&i] - to address diversity & inclusion report work group

Possible community practice: Ignore email (auto delete with personal filter rules) if not following this standard.

Content tags (optional):
[minutes] - tag meeting minutes and notes
[intro] - tag self-introductions
[grimoire] - tag for GrimoireLab related emails
[ghdata] - tag for GHData related emails
[cregit] - tag for Cregit related emails
[prospector] - tag for Prospector related emails

**Comment by germonprez** [comment]
This is a good list. 

Would it be as: [all][intro]

or: [software]

??

**Comment by jgbarah** [comment]
Maybe we could revisit this, and add this to some document here, and/or in the website? I think the idea is good...

**Comment by GeorgLink** [comment]
This could live in the community handbook. However, so far we have not had a direct need for prefixes on emails.

**Comment by jgbarah** [comment]
@GeorgLink what do you think: we better change the title of this issue to somehow include "handbook", we better close it for now?

In any case, I think at least we're using prefixes such as [wg-d&i] or [wg-gmd] for matters specific for working groups..,

**Comment by GeorgLink** [comment]
Sure, we can close for now.

>
