### ISSUE TITLE
Request that GSoC students make their submission repos private

### ISSUE THREAD

**Issue by germonprez** [chaoss/governance#86]
@GeorgLink what do you think about having the students submit private repos for their GSoC microtasks? They could make the repos available to organizers and mentors. This came up today in the Community Call

**Comment by GeorgLink** [comment]
hm... I'm not a fan of the private repos because it goes against the "openness" paradigm of open source but I don't see major benefits or detriments and will defer to the majority of mentors. 

Organizationally, we would have to provide a list of github accounts of all mentors and org admins that need to be given access to private repos.

**Comment by germonprez** [comment]
It is because last year we had a concern that an applicant was looking at another solution.

**Comment by GeorgLink** [comment]
I remember. If the mentors want private repos this year, we can amend our
instructions.

**Comment by jgbarah** [comment]
In general, that should not be a problem (I mean, students looking at other repos). First, you have the dates, if that's important to detect copycats. Second, usually is the process and the interaction what matters. And we can always ask for additional microtasks, if we're in doubt.

Maybe we need to help students understand that copying and being copied is not a bad thing, specially if we request them to say that.

Additionally, they can also keep their repos private until the moment they decide (even the same day application closes), but that would prevent us from having a look and recommend, so they can improve.

If you want, I could write some short text for the document where students link their repos, explaining this, if you agree that public is more convenient...

**Comment by germonprez** [comment]
Thanks for this @jgbarah 

Sounds like the path is to keep the repos public (as is). Perhaps include the following statement? 

4. Using and submitting other people's work as your own is not allowed. If you use other people's work, be sure to acknowledge their work in your submission. 

Something like this.

**Comment by aswanipranjal** [comment]
@germonprez @jgbarah @GeorgLink I too think that students making the repositories private might be a bad thing. Students might want to look at other solutions if they are stuck or just want inspiration and that should be okay as long as they acknowledge the original source.
